### PR TITLE
Jwt - Updates wave 1

### PR DESCRIPTION
**Pull request by jregistr**
Hi Ryan, 
I merged the master branch into my local copy of the JWT branch and have added a few commits. I added the jwt packages to the vendor directory and started updating the tests. I'm doing this as a preliminary test for how this process is going to work. Please let me know of anything I need to do to get this merged in. 

PS: I apologize in advance for any egregious errors, I am quite new to the Go language.

Thanks!

### CODE REVIEW

**Comment by ryantxu** [comment]
hymmm -- I'm not sure how to look at or evaluate 1,707 files!  can you try again with a more limited PR?

image

**Comment by ryantxu** [comment]
I merged grafana master... so maybe that will help?

**Comment by jregistr** [comment]
I'll update this branch 🤞

**Comment by jregistr** [comment]
@ryantxu I rebased this branch onto your latest jwt branch. 🎉

**Pull request merged**
